export { manifest } from './manifest'
export { ParcourTemplateEditor } from './components/parcours-template-editor'
export { EmailTemplateEditor } from './components/email-template-editor'
export { saveParcourTemplate, duplicateParcourTemplate, archiveParcourTemplate } from './actions/save-parcours-template'
export type { ParcourTemplate, Stage } from './actions/save-parcours-template'
export { saveEmailTemplate, resetEmailTemplate, DEFAULT_EMAIL_TEMPLATES } from './actions/save-email-template'
export type { EmailTemplate } from './actions/save-email-template'
export { useParcourTemplates } from './hooks/use-parcours-templates'
export { useEmailTemplates } from './hooks/use-email-templates'
