export { manifest } from './manifest'
export { createSupportTicket } from './actions/create-support-ticket'
export { getSupportTickets } from './actions/get-support-tickets'
export { updateTicketStatus } from './actions/update-ticket-status'
export { uploadScreenshot } from './actions/upload-screenshot'
export { useSupportTickets, useCreateSupportTicket, useUpdateTicketStatus } from './hooks/use-support-tickets'
export { useSupportTicketsRealtime } from './hooks/use-support-tickets-realtime'
export { ReportIssueDialog } from './components/report-issue-dialog'
export { MyTicketsList } from './components/my-tickets-list'
export { TicketStatusBadge } from './components/ticket-status-badge'
export { FaqPage } from './components/faq-page'
export { ClientSupportTab } from './components/client-support-tab'
export type { SupportTicket, CreateTicketInput, TicketType, TicketStatus } from './types/support.types'
