export { coreDashboardManifest } from './manifest'
export { CoreDashboard } from './components/core-dashboard'
export { LabTeasingCard } from './components/lab-teasing-card'
export { useClientConfig } from './hooks/use-client-config'
export { getClientConfig } from './actions/get-client-config'
export { getTeasingEligibility } from './actions/get-teasing-eligibility'
export type { TeasingEligibility } from './actions/get-teasing-eligibility'
